# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Gradle Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Save to CHANGELOG
        run: echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md
        
      - name: Set up JDK 17.0.2+8
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '17.0.2+8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "MinePlayAPI"
          path:  |
            ./build/libs/MinePlayAPI*.jar
            CHANGELOG.md
      - name: get version and date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.date }}
          body: ${{ steps.changelog.outputs.changelog }}
          fail_on_unmatched_files: true
          files: "./build/libs/MinePlayAPI*.jar"
          draft: false
          prerelease: false
