# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Gradle Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Save to CHANGELOG
        run: echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md
        
      - name: Set up JDK 17.0.2+8
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '17.0.2+8'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build with Gradle
        run: gradle --build-cache shadowJar --parallel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "MinePlayAPI"
          path:  |
            ./build/libs/MinePlayAPI*.jar
            CHANGELOG.md
      - name: get version and date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: MinePlayAPI_1.0-SNAPSHOT
          body: ${{ steps.changelog.outputs.changelog }}
          fail_on_unmatched_files: true
          files: "./build/libs/MinePlayAPI*.jar"
          draft: false
          prerelease: false
